import { useEffect, useState } from "react";
import { MastersClient, type DeckDto, type StudyPlanDto } from "../api/client";
import { Badge, Card } from "./ui";

/**
 * Read-only study view (Phase 3a/3b, FR-13/14/15): a project's flashcard decks (with due counts)
 * plus its active adaptive study plan. Decks and the plan are generated by the agent from project
 * material and review history (`study.*` tools); reviews run in chat via SM-2 scheduling.
 */
export function Study({ client, projectId }: { client: MastersClient; projectId: string }) {
  const [decks, setDecks] = useState<DeckDto[] | null>(null);
  const [plan, setPlan] = useState<StudyPlanDto | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    client
      .listDecks(projectId)
      .then(setDecks)
      .catch((e) => setError(String(e)));
    client
      .studyPlan(projectId)
      .then(setPlan)
      .catch((e) => setError(String(e)));
  }, [client, projectId]);

  if (error) return <div className="p-4 text-sm text-danger">{error}</div>;
  if (!decks) return <div className="p-4 text-sm text-muted">Loading decks…</div>;

  return (
    <div className="space-y-4 overflow-y-auto p-4 text-sm">
      <section className="space-y-2">
        <h3 className="text-xs font-semibold uppercase tracking-wide text-muted">Decks</h3>
        {decks.length === 0 ? (
          <div className="text-sm text-muted">No flashcard decks yet.</div>
        ) : (
          decks.map((d) => (
            <Card key={d.name} className="flex items-center justify-between p-3">
              <div className="font-medium text-text">{d.name}</div>
              <div className="flex items-center gap-2 text-xs text-muted">
                {d.cards} card{d.cards === 1 ? "" : "s"}
                {d.due > 0 && <Badge variant="tool">{d.due} due</Badge>}
              </div>
            </Card>
          ))
        )}
      </section>

      <section className="space-y-2">
        <h3 className="text-xs font-semibold uppercase tracking-wide text-muted">Study plan</h3>
        {plan ? <StudyPlanCard plan={plan} /> : <div className="text-sm text-muted">No study plan yet.</div>}
      </section>
    </div>
  );
}

function StudyPlanCard({ plan }: { plan: StudyPlanDto }) {
  const days = Math.ceil((plan.deadline_at - Date.now()) / 86_400_000);
  const deadline =
    days > 0 ? `${days} day${days === 1 ? "" : "s"} left` : days === 0 ? "due today" : "past deadline";
  return (
    <Card className="p-3">
      <div className="flex items-center justify-between">
        <div className="font-medium text-text">{plan.title}</div>
        <div className="text-xs text-muted">{deadline}</div>
      </div>
      <pre className="mt-2 whitespace-pre-wrap font-sans text-text">{plan.body}</pre>
    </Card>
  );
}
