//! OpenAPI aggregation (utoipa). The emitted `openapi.json` is the single source of truth
//! for the generated TypeScript client (docs/02 §4).

use utoipa::OpenApi;

use getmasters_proto::{
    AddGrantRequest, AssetDto, AuditEntryDto, AvailableHarnessDto, BriefingDto, BundleImportResult,
    CatalogDto, CatalogStatusDto, ClientCommand, ConfigCheckDto, ConfigCheckItem, ConnectorDto,
    CreateConnectorRequest, CreateProjectRequest, CreateScheduleRequest, CreateSessionRequest,
    CreateTeamRequest, DeckDto, DefaultMasterDto, DocumentDto, EmailSettingsDto,
    EmailSettingsUpdate, EnvironmentDto, ErrorDto, EventDto, ExtensionDto, FilePreview,
    FolderGrant, GroupMasterErrorDto, GroupPostRequest, GroupPostResult, HealthDto,
    InvestingWorkspaceDto, KnowledgeStatusDto, MasterDto, MasterRunResult, MasterSummaryDto,
    MemoryDto, MessageDto, ProjectDto, ProviderStateDto, ProvidersDto, QuickChatRequest, QuoteDto,
    RankedMasterDto, RecipeDto, RecipeParamDto, RecipeRunResult, RecipeSummaryDto, RevertResult,
    RouteBriefRequest, RouteResultDto, RunMasterRequest, RunRecipeRequest, RunTeamRequest,
    ScheduleDto, ScheduledRunDto, SecretUpdate, SendMessageRequest, ServerEvent, SessionDto,
    SetConnectorEnabledRequest, SetExtensionRequest, SetInstructionsRequest, SetScheduleRequest,
    SettingsDto, SettingsUpdate, SkillDto, StudyPlanDto, TeamBundle, TeamDto, TeamRunResult,
    TeamSummaryDto,
};

#[derive(OpenApi)]
#[openapi(
    info(title = "Masters daemon API", description = "Local loopback API exposed by getmastersd."),
    paths(
        crate::routes::health::health,
        crate::routes::sessions::create,
        crate::routes::sessions::list,
        crate::routes::sessions::delete,
        crate::routes::sessions::list_audit,
        crate::routes::sessions::list_events,
        crate::routes::sessions::revert,
        crate::routes::messages::list,
        crate::routes::messages::send,
        crate::routes::settings::get,
        crate::routes::settings::update,
        crate::routes::settings::providers,
        crate::routes::settings::environment,
        crate::routes::settings::check,
        crate::routes::settings::get_email,
        crate::routes::settings::update_email,
        crate::routes::settings::set_secret,
        crate::routes::settings::delete_secret,
        crate::routes::projects::create,
        crate::routes::projects::list,
        crate::routes::projects::get,
        crate::routes::projects::add_grant,
        crate::routes::projects::set_instructions,
        crate::routes::projects::list_memories,
        crate::routes::projects::list_skills,
        crate::routes::projects::list_decks,
        crate::routes::projects::study_plan,
        crate::routes::investing::ensure_workspace,
        crate::routes::investing::list_assets,
        crate::routes::investing::untrack_asset,
        crate::routes::investing::list_quotes,
        crate::routes::investing::list_briefings,
        crate::routes::recipes::save,
        crate::routes::recipes::list,
        crate::routes::recipes::get,
        crate::routes::recipes::run,
        crate::routes::masters::save,
        crate::routes::masters::list,
        crate::routes::masters::get,
        crate::routes::masters::delete,
        crate::routes::masters::run,
        crate::routes::masters_global::save,
        crate::routes::masters_global::list,
        crate::routes::masters_global::get,
        crate::routes::masters_global::delete,
        crate::routes::masters_global::templates,
        crate::routes::masters_global::get_default,
        crate::routes::masters_global::set_default,
        crate::routes::masters_global::quickchat,
        crate::routes::teams::save,
        crate::routes::teams::list,
        crate::routes::teams::get,
        crate::routes::teams::delete,
        crate::routes::teams::route,
        crate::routes::teams::run,
        crate::routes::bundles::export,
        crate::routes::bundles::import,
        crate::routes::group::start,
        crate::routes::group::post,
        crate::routes::connectors::save,
        crate::routes::connectors::list,
        crate::routes::connectors::set_enabled,
        crate::routes::connectors::delete,
        crate::routes::schedules::create,
        crate::routes::schedules::list,
        crate::routes::schedules::set,
        crate::routes::schedules::delete,
        crate::routes::schedules::runs,
        crate::routes::projects::knowledge_status,
        crate::routes::projects::list_extensions,
        crate::routes::projects::set_extension,
        crate::routes::acp::harnesses,
        crate::routes::skills_global::list,
        crate::routes::skills_global::get,
        crate::routes::skills_global::delete,
        crate::routes::catalog::sync,
        crate::routes::catalog::status,
    ),
    components(schemas(
        HealthDto,
        CreateSessionRequest,
        SessionDto,
        MessageDto,
        SendMessageRequest,
        AuditEntryDto,
        EventDto,
        ErrorDto,
        SettingsDto,
        SettingsUpdate,
        ProviderStateDto,
        ProvidersDto,
        EnvironmentDto,
        ConfigCheckDto,
        ConfigCheckItem,
        EmailSettingsDto,
        EmailSettingsUpdate,
        SecretUpdate,
        RevertResult,
        ProjectDto,
        CreateProjectRequest,
        AddGrantRequest,
        SetInstructionsRequest,
        MemoryDto,
        SkillDto,
        CatalogDto,
        CatalogStatusDto,
        DeckDto,
        StudyPlanDto,
        AssetDto,
        QuoteDto,
        InvestingWorkspaceDto,
        BriefingDto,
        RecipeDto,
        RecipeParamDto,
        RecipeSummaryDto,
        RunRecipeRequest,
        RecipeRunResult,
        MasterDto,
        MasterSummaryDto,
        RunMasterRequest,
        MasterRunResult,
        DefaultMasterDto,
        QuickChatRequest,
        AvailableHarnessDto,
        TeamDto,
        TeamSummaryDto,
        CreateTeamRequest,
        RankedMasterDto,
        RouteBriefRequest,
        RouteResultDto,
        RunTeamRequest,
        TeamRunResult,
        TeamBundle,
        BundleImportResult,
        GroupPostRequest,
        GroupPostResult,
        GroupMasterErrorDto,
        ConnectorDto,
        CreateConnectorRequest,
        SetConnectorEnabledRequest,
        ScheduleDto,
        CreateScheduleRequest,
        SetScheduleRequest,
        ScheduledRunDto,
        ExtensionDto,
        SetExtensionRequest,
        KnowledgeStatusDto,
        DocumentDto,
        FolderGrant,
        // WS envelopes have no REST path but are part of the contract, so the TS client gets types.
        ClientCommand,
        ServerEvent,
        FilePreview,
    )),
    tags(
        (name = "system", description = "Health and metadata"),
        (name = "sessions", description = "Sessions and messages"),
        (name = "settings", description = "Settings and secrets"),
    )
)]
pub struct ApiDoc;
